# Refers to the version 1.2 of the .dockstore.yml schema
version: 1.2

# An array of workflows.
workflows:

  - name: CAMRA-Assembly_Quality_Control-WDL
    subclass: WDL
    primaryDescriptorPath: /Workflows/CAMRA_QC_WF.wdl
    readMePath: /README.md
    latestTagAsDefault: True
    authors:
      - orcid: 0009-0008-5199-2990 # Daniella Matute
      - name: Thomas Clarke
        email: toby.h.clarke@gmail.com
    branches:
      - main 

    
  - name: CAMRAGenomeAssemblyWDL
    subclass: WDL
    primaryDescriptorPath: /Workflows/CAMRA_ASM_WF.wdl
    readMePath: /README.md
    latestTagAsDefault: True
    authors:
      - orcid: 0009-0008-5199-2990 #Daniella Matute
      - name: Andrew LaPointe
        email: andrewrlapointe@gmail.com
        

  - name: CAMRA_AMR_WF_NIGERIA_WDL
    subclass: WDL
    primaryDescriptorPath: /Workflows/CAMRA_AMR_WF_NIGERIA.wdl
    readMePath: /README.md
    latestTagAsDefault: True
    authors:
      - orcid: 0009-0008-5199-2990 #Daniella Matute
    branches:
      - main 

  - name: CAMRA_MAKEFILE_WF_WDL
    subclass: WDL
    primaryDescriptorPath: /Workflows/CAMRA_MAKE_FILELIST_WF.wdl
    readMePath: /README.md
    latestTagAsDefault: True
    authors:
      - orcid: 0009-0008-5199-2990 #Daniella Matute
    branches:
      - main
  
  - name: CAMRA_PANGENOME_WF_WDL
    subclass: WDL
    primaryDescriptorPath: /Workflows/CAMRA_PANGENOME2_WF.wdl
    readMePath: /README.md
    latestTagAsDefault: True
    authors:
      - orcid: 0009-0008-5199-2990 #Daniella Matute
    branches:
      - main
  
  - name: CAMRA_GETGB_WF_WDL
    subclass: WDL
    primaryDescriptorPath: /Workflows/CAMRA_GETGENBANK_WF.wdl
    readMePath: /README.md
    latestTagAsDefault: True
    authors:
      - orcid: 0009-0008-5199-2990 #Daniella Matute
    branches:
      - main

  - name: CAMRA_PANGENOME_NOBLAST_WF
    subclass: WDL
    primaryDescriptorPath: /Workflows/CAMRA_PANGENOME_NOBLAST_WF.wdl
    readMePath: /README.md
    latestTagAsDefault: True
    authors:
      - orcid: 0009-0008-5199-2990 #Daniella Matute
    branches:
      - main
  
